name: Changelog Generator
description: Automatically generates a changelog based on commit messages.

on:
  push:
    branches:
      - main  # Change this to the branch you're working on for releases

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow the action to push changes to the repository

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Create or update CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true" # Skip creating a version file, only update the changelog
          git-message: "docs: update CHANGELOG.md [skip ci]"
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"