name: Unit Testing (Busted Framework)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install LuaJIT and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit luarocks

      - name: Install Busted Framework
        run: sudo luarocks install busted

      - name: Run Tests
        run: busted spec/